// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuajjpcuegjubwqdxoev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1YWpqcGN1ZWdqdWJ3cWR4b2V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjM1ODQsImV4cCI6MjA2NTUzOTU4NH0.349aoxHqWjY7afDzXCANGhfXHIlXKxp-crMw7mXrzdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);